name: CI

on:
  push: 
    branches: 
      - master

jobs:
  build-and-push: 
    name: 'Build and Push'
    runs-on: ubunto-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build docker image
      run: docker build -t kaugoncalves/nlw.journey.api: .